### ISSUE TITLE
Namespaces not exported in version 1.24.0

### ISSUE THREAD

**Issue by belinde** [Mangopay/mangopay2-nodejs-sdk#295]
I tried to upgrade the package, but  model's namespaces are not exported anymore. They still can be accessed `import`ing the internal definitions, but it doesn't feel right and is not intuitive.

The types in those namespaces where really important in my codebase, and being exported in the previous index.d.ts should be preserved in a normal release.

Here some examples

### BrowserInfoData
Before: 
```typescript
import MangoPay from 'mangopay2-nodejs-sdk';
let x: MangoPay.BrowserInfoData;
```
After:
```typescript
import { Base } from 'mangopay2-nodejs-sdk/typings/base';
let x: Base.BrowserInfoData;
```

### EventType
Before: 
```typescript
import MangoPay from 'mangopay2-nodejs-sdk';
let x: MangoPay.event.EventType;
```
After:
```typescript
import { event } from 'mangopay2-nodejs-sdk/typings/models/event';
let x: event.EventType;
```

### KYCLevel
Before: 
```typescript
import MangoPay from 'mangopay2-nodejs-sdk';
let x: MangoPay.user.KYCLevel;
```
After:
```typescript
import { user } from 'mangopay2-nodejs-sdk/typings/models/user';
let x: user.KYCLevel;
```

### KycDocumentType, DocumentStatus
Before: 
```typescript
import MangoPay from 'mangopay2-nodejs-sdk';
let x: MangoPay.kycDocument.KycDocumentType;
let y: MangoPay.kycDocument.DocumentStatus;
```
After:
```typescript
import { kycDocument } from 'mangopay2-nodejs-sdk/typings/models/kycDocument';
let x: kycDocument.KycDocumentType;
let y: kycDocument.DocumentStatus;
```

### LegalPersonType, UserLegalData, UserNaturalData
Before: 
```typescript
import MangoPay from 'mangopay2-nodejs-sdk';
let x: MagoPay.user.LegalPersonType;
let y: MangoPay.user.UserLegalData;
let z: MangoPay.user.UserNaturalData;
```
After:
```typescript
import { user } from 'mangopay2-nodejs-sdk/typings/models/user';
let x: user.LegalPersonType;
let y: user.UserLegalData;
let z: user.UserNaturalData;
```

### AddressData
Before: 
```typescript
import MangoPay from 'mangopay2-nodejs-sdk';
let x: MagoPay.address.AddressData;
```
After:
```typescript
import { address } from 'mangopay2-nodejs-sdk/typings/models/address';
let x: address.AddressData;
```

### MoneyData
Before: 
```typescript
import MangoPay from 'mangopay2-nodejs-sdk';
let x: MagoPay.MoneyData;
```
After:
```typescript
import { money } from 'mangopay2-nodejs-sdk/typings/models/money';
let x: money.MoneyData;
```

**Comment by iulian03** [comment]
Hi @belinde,

Sorry about this, we made a [pull request](https://github.com/Mangopay/mangopay2-nodejs-sdk/pull/296) that should fix it.

Accessing previous namespaces should remain the same, but there are some small changes with the objects that were not previously contained in any namespace. We will include this in the release notes. For example:

The "base" namespace will include now stuff like RequestOptions, Config, PaginationOptions, etc. Those objects were previously accessed by `MangoPay.BrowserInfoData` and now they should be accessed by `MangoPay.base.BrowserInfoData`. This change will make life easier for future development, by keeping the type declarations better organised.

We will also add some tests to be sure that namespace accessing will not be a problem.

**Comment by belinde** [comment]
Updated to 1.24.1, `CurrencyISO` and `CountryISO` are still missing.

**Comment by iulian03** [comment]
@belinde You're right. We will include those as well in the next release. Is this affecting your existing code at this moment? I'm asking because we didn't change the location of CurrencyISO and CountryISO in some time and it would be strange if it did.

**Comment by belinde** [comment]
Sorry, my fault: I didn't notice that we were already importing the inner files. That said, those two types are really useful, I'll wait the next release to import them properly. Sorry again.

**Comment by iulian03** [comment]
Hey, @belinde . We just added the exports for CurrencyISO and CountryISO in the latest release.

**Comment by belinde** [comment]
Updated and perfectly working, thank you
